# edge_admin/lib/edge_admin/nodes/schemas/cluster.ex
defmodule EdgeAdmin.Nodes.Schemas.Cluster do
  @moduledoc """
  Schema for edge clusters.

  Each cluster represents an isolated Netmaker network (VPN) with its own IPv4 range.
  Nodes within a cluster can communicate with each other via the VPN.

  ## Fields

  - `name` - Cluster name (lowercase alphanumeric with hyphens, max 24 chars)
  - `ipv4_range` - CIDR notation for the cluster's VPN network (e.g., "100.64.1.0/24")
  - `node_limit` - Maximum nodes allowed in this cluster (null means no limit)
  - `network_name` - Virtual field: Netmaker network name (cluster-{name})
  - `vpn_domain` - Virtual field: VPN domain suffix for nodes in this cluster
  - `node_count` - Virtual field: Number of nodes in this cluster
  """
  use EdgeAdmin.Schema

  alias EdgeAdmin.Vpn

  # /31 and /32 are unusable: /32 has 1 IP (consumed by the first admin gateway),
  # /31 has 2 IPs (both consumed before any edge node can enroll).
  @min_prefix 30

  @type t :: %__MODULE__{
          id: String.t(),
          name: String.t(),
          ipv4_range: String.t(),
          node_limit: integer() | nil,
          network_name: String.t() | nil,
          vpn_domain: String.t() | nil,
          node_count: integer() | nil,
          nodes: [EdgeAdmin.Nodes.Schemas.Node.t()] | Ecto.Association.NotLoaded.t(),
          inserted_at: DateTime.t(),
          updated_at: DateTime.t()
        }

  @derive {
    Flop.Schema,
    filterable: [:name, :ipv4_range, :node_limit, :inserted_at],
    sortable: [:name, :ipv4_range, :node_limit, :inserted_at, :updated_at],
    default_order: %{
      order_by: [:inserted_at],
      order_directions: [:desc]
    }
  }

  schema "clusters" do
    field(:name, :string)
    field(:ipv4_range, :string)
    field(:node_limit, :integer)
    field(:network_name, :string, virtual: true)
    field(:vpn_domain, :string, virtual: true)
    field(:node_count, :integer, virtual: true)

    has_many(:nodes, EdgeAdmin.Nodes.Schemas.Node)
    has_many(:enrollment_keys, EdgeAdmin.Nodes.Schemas.EnrollmentKey)

    timestamps()
  end

  @doc false
  def changeset(cluster, attrs) do
    cluster
    |> cast(attrs, [:name, :ipv4_range, :node_limit])
    |> maybe_generate_name()
    |> maybe_generate_ipv4_range()
    |> validate_required([:name, :ipv4_range])
    |> validate_length(:name, max: 24)
    |> validate_format(:name, ~r/^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/)
    |> validate_number(:node_limit, greater_than: 0)
    |> validate_ipv4_cidr_format()
    |> validate_ipv4_exclusions()
    |> validate_cidr_minimum_prefix()
    |> validate_node_limit_fits_cidr()
    |> unique_constraint(:name)
    |> unique_constraint(:ipv4_range)
  end

  @doc """
  Returns the Netmaker network name for this cluster.

  ## Format
  `cluster-{name}`

  ## Examples

      iex> network_name(%Cluster{name: "prod"})
      "cluster-prod"
  """
  @spec network_name(t()) :: String.t()
  def network_name(%__MODULE__{name: name}), do: Vpn.build_network_name(name, prefix: :node)

  @doc """
  Returns the VPN domain suffix for nodes in this cluster.

  ## Format
  `cluster-{name}.{domain}`

  where domain is configured via `NETMAKER_DEFAULT_DOMAIN` (default: `nm.internal`)

  ## Examples

      iex> vpn_domain(%Cluster{name: "prod"})
      "cluster-prod.nm.internal"
  """
  @spec vpn_domain(t()) :: String.t()
  def vpn_domain(%__MODULE__{name: name}) do
    Vpn.build_vpn_domain(Vpn.build_network_name(name, prefix: :node))
  end

  @doc """
  Returns the number of nodes in this cluster.

  ## Requirements
  Requires nodes association to be preloaded.

  ## Returns
  - Integer count if nodes preloaded
  - `0` if nodes not loaded

  ## Examples

      iex> node_count(%Cluster{nodes: [%Node{}, %Node{}]})
      2

      iex> node_count(%Cluster{nodes: %Ecto.Association.NotLoaded{}})
      0
  """
  @spec node_count(t()) :: non_neg_integer()
  def node_count(%__MODULE__{nodes: nodes}) when is_list(nodes), do: length(nodes)
  def node_count(%__MODULE__{}), do: 0

  # Private helper functions

  defp maybe_generate_name(changeset) do
    if get_field(changeset, :name) do
      changeset
    else
      # Generate 12-char random alphanumeric name
      random_name =
        9
        |> :crypto.strong_rand_bytes()
        |> Base.encode32(case: :lower, padding: false)
        |> String.slice(0..11)

      put_change(changeset, :name, random_name)
    end
  end

  defp maybe_generate_ipv4_range(changeset) do
    if get_field(changeset, :ipv4_range) do
      changeset
    else
      # Will be generated by Nodes context if needed
      changeset
    end
  end

  # Private validation functions

  defp validate_ipv4_cidr_format(changeset) do
    validate_change(changeset, :ipv4_range, fn _, value ->
      case Vpn.parse_cidr(value) do
        {:ok, _} -> []
        {:error, reason} -> [ipv4_range: reason]
      end
    end)
  end

  defp validate_ipv4_exclusions(changeset) do
    validate_change(changeset, :ipv4_range, fn _, value ->
      case Vpn.parse_cidr(value) do
        {:ok, {ip_tuple, _prefix}} ->
          if excluded_range?(ip_tuple) do
            [ipv4_range: "cannot use private, loopback, link-local, or multicast ranges"]
          else
            []
          end

        {:error, _} ->
          []
      end
    end)
  end

  defp excluded_range?({a, _, _, _}) do
    a in [0, 10, 127, 169, 172, 192, 224, 240, 255]
  end

  defp validate_cidr_minimum_prefix(changeset) do
    validate_change(changeset, :ipv4_range, fn _, value ->
      case Vpn.parse_cidr(value) do
        {:ok, {_ip, prefix}} when prefix > @min_prefix ->
          [
            ipv4_range:
              "prefix /#{prefix} is too small — minimum is /#{@min_prefix} (#{cidr_capacity(@min_prefix)} IPs)"
          ]

        _ ->
          []
      end
    end)
  end

  # Validates node_limit does not exceed usable CIDR capacity after reservations.
  # Only fires when both fields are present and the CIDR is already valid.
  defp validate_node_limit_fits_cidr(changeset) do
    with limit when not is_nil(limit) <- get_field(changeset, :node_limit),
         cidr when not is_nil(cidr) <- get_field(changeset, :ipv4_range),
         {:ok, {_ip, prefix}} <- Vpn.parse_cidr(cidr) do
      reservation = Vpn.admin_slot_reservation() + Vpn.node_slot_reservation()
      max_limit = cidr_capacity(prefix) - reservation

      if limit > max_limit do
        add_error(
          changeset,
          :node_limit,
          "cannot exceed #{max_limit} for /#{prefix} (#{cidr_capacity(prefix)} IPs minus #{reservation} reserved slots)"
        )
      else
        changeset
      end
    else
      _ -> changeset
    end
  end

  # 2^(32 - prefix) — full address count, no broadcast/network exclusion
  # (WireGuard assigns all addresses including .0 and .255)
  defp cidr_capacity(prefix), do: Integer.pow(2, 32 - prefix)
end
