// edge_vpn/internal/headscale/client.go
package headscale

import (
	"fmt"
	"os/exec"
	"regexp"
	"strings"
)

// Client handles interactions with Headscale CLI
type Client struct {
	headscalePath string
}

// NewClient creates a new Headscale client
func NewClient() *Client {
	return &Client{
		headscalePath: "/usr/local/bin/headscale",
	}
}

// CreateAPIKey creates a new API key using Headscale CLI
func (c *Client) CreateAPIKey(expirationDays int) (string, error) {
	expiration := fmt.Sprintf("%dd", expirationDays)

	cmd := exec.Command(c.headscalePath, "apikeys", "create", "--expiration", expiration)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("failed to create API key: %w, output: %s", err, string(output))
	}

	// Parse the API key from output
	apiKey, err := c.parseAPIKeyFromOutput(string(output))
	if err != nil {
		return "", fmt.Errorf("failed to parse API key from output: %w", err)
	}

	return apiKey, nil
}

// parseAPIKeyFromOutput extracts the API key from CLI output
func (c *Client) parseAPIKeyFromOutput(output string) (string, error) {
	lines := strings.Split(strings.TrimSpace(output), "\n")

	// Try multiple patterns to find the API key
	patterns := []string{
		// Pattern 1: Keys that start with "hs_"
		`hs_[a-zA-Z0-9]+`,
		// Pattern 2: Keys that look like base64/alphanumeric tokens (what we're seeing)
		`[a-zA-Z0-9]{7}\.[a-zA-Z0-9]{32,}`,
		// Pattern 3: Any long alphanumeric string with dots
		`[a-zA-Z0-9]+\.[a-zA-Z0-9]{20,}`,
		// Pattern 4: Just look for the last line if it's a token-like string
		`^[a-zA-Z0-9]+\.[a-zA-Z0-9]+$`,
	}

	for _, pattern := range patterns {
		re := regexp.MustCompile(pattern)
		if matches := re.FindStringSubmatch(output); len(matches) > 0 {
			return matches[0], nil
		}
	}

	// Fallback: if output looks like a single token on the last line
	if len(lines) > 0 {
		lastLine := strings.TrimSpace(lines[len(lines)-1])
		// Check if the last line looks like an API key (has dots and is long enough)
		if strings.Contains(lastLine, ".") && len(lastLine) > 20 && !strings.Contains(lastLine, " ") {
			return lastLine, nil
		}
	}

	return "", fmt.Errorf("no API key found in output: %s", output)
}

// ValidateAPIKey tests if an API key is valid by making a simple API call
func (c *Client) ValidateAPIKey(apiKey string) error {
	// Use the HTTP API instead of CLI for validation since we have the key
	// But for now, let's use a simpler approach - just check the format
	if len(apiKey) < 10 || !strings.Contains(apiKey, ".") {
		return fmt.Errorf("API key format appears invalid")
	}

	// TODO: We could make an HTTP request to validate, but for now assume it's valid
	// if it was just generated by headscale
	return nil
}

// ExpireAPIKey expires an existing API key
func (c *Client) ExpireAPIKey(keyPrefix string) error {
	cmd := exec.Command(c.headscalePath, "apikeys", "expire", keyPrefix)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to expire API key: %w, output: %s", err, string(output))
	}
	return nil
}

// GetKeyPrefix extracts the prefix from a full API key for expiration
func (c *Client) GetKeyPrefix(apiKey string) string {
	// For keys like "XNXjM9T.Y4uBzsFYMfxvEaAPqPGR0kFhEK2yC3Ax"
	// Use the part before the first dot as prefix
	if dotIndex := strings.Index(apiKey, "."); dotIndex > 0 {
		return apiKey[:dotIndex]
	}

	// Fallback: use first 8 characters
	if len(apiKey) > 8 {
		return apiKey[:8]
	}
	return apiKey
}
