{{- /* deploy/k8s/charts/edge-admin/templates/secret.yaml */ -}}
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-admin.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-admin.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secrets.secretKeyBase | quote }}
  MASTER_KEY: {{ .Values.secrets.masterKey | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  NETMAKER_MASTER_KEY: {{ .Values.secrets.netmakerMasterKey | quote }}
  NETMAKER_SUPERADMIN_PASSWORD: {{ .Values.secrets.netmakerSuperadminPassword | quote }}
  VPN_CLUSTER_COOKIE: {{ .Values.secrets.vpnClusterCookie | quote }}
  {{- if .Values.secrets.eventBrokerNatsToken }}
  EVENT_BROKER_NATS_TOKEN: {{ .Values.secrets.eventBrokerNatsToken | quote }}
  {{- end }}
  {{- if .Values.secrets.eventBrokerNatsUsername }}
  EVENT_BROKER_NATS_USERNAME: {{ .Values.secrets.eventBrokerNatsUsername | quote }}
  EVENT_BROKER_NATS_PASSWORD: {{ .Values.secrets.eventBrokerNatsPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.eventBrokerNatsNkeySeed }}
  EVENT_BROKER_NATS_NKEY_SEED: {{ .Values.secrets.eventBrokerNatsNkeySeed | quote }}
  {{- end }}
  {{- if .Values.secrets.eventBrokerNatsJwt }}
  EVENT_BROKER_NATS_JWT: {{ .Values.secrets.eventBrokerNatsJwt | quote }}
  {{- end }}
  {{- if .Values.secrets.eventBrokerKafkaUsername }}
  EVENT_BROKER_KAFKA_USERNAME: {{ .Values.secrets.eventBrokerKafkaUsername | quote }}
  EVENT_BROKER_KAFKA_PASSWORD: {{ .Values.secrets.eventBrokerKafkaPassword | quote }}
  {{- end }}
{{- end }}
