{{- /* deploy/k8s/charts/edge-vpn/templates/secret.yaml */ -}}
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-vpn.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-vpn.labels" . | nindent 4 }}
type: Opaque
stringData:
  MASTER_KEY: {{ .Values.secrets.masterKey | quote }}
  SQL_PASS: {{ .Values.secrets.dbPassword | quote }}
  MQ_PASSWORD: {{ .Values.secrets.mqPassword | quote }}
{{- end }}
