#!/bin/bash
# deploy/production/compose/edge_admin/start

set -o errexit
set -o pipefail
set -o nounset

echo "Running migrations..."
/app/bin/migrate

echo "Bootstrapping Netmaker superadmin..."
/app/bin/create_netmaker_superadmin

echo "Bootstrapping default cluster..."
/app/bin/create_default_cluster

echo "Starting server..."
exec /app/bin/server
