# deploy/local/edge.yml
networks:
  local_edge_core:
    name: local_edge_core

volumes:
  local_edge_agent_data: {}
  local_edge_agent_deps: {}
  local_edge_agent_build: {}
  local_edge_agent_netclient_data: {}
  local_edge_agent_2_data: {}
  local_edge_agent_2_deps: {}
  local_edge_agent_2_build: {}
  local_edge_agent_2_netclient_data: {}

services:
  # Edge Agents
  edge_agent:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/edge_agent/Dockerfile
    image: local_edge_agent
    container_name: local_edge_agent
    volumes:
      - ../../edge_agent:/app:z
      - ../../nexmaker:/nexmaker:z
      - local_edge_agent_deps:/app/deps
      - local_edge_agent_build:/app/_build
      - local_edge_agent_data:/app/data
      - local_edge_agent_netclient_data:/etc/netclient
      - /etc/resolv.conf:/etc/resolv.conf:rw
      - /:/host:ro
    env_file:
      - ./.envs/.edge_agent
    network_mode: host
    privileged: true
    ports:
      - "44000:44000"
      - "43128:43128"
      - "41080:41080"

  edge_agent_2:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/edge_agent/Dockerfile
    image: local_edge_agent
    container_name: local_edge_agent_2
    networks:
      - local_edge_core
    volumes:
      - ../../edge_agent:/app:z
      - ../../nexmaker:/nexmaker:z
      - local_edge_agent_2_deps:/app/deps
      - local_edge_agent_2_build:/app/_build
      - local_edge_agent_2_data:/app/data
      - local_edge_agent_2_netclient_data:/etc/netclient
      - /:/host:ro
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUBLIC_ENROLLMENT_KEY_URL=http://edge_admin:44000/api/clusters/default/enrollment_keys/public
      - WG_QUICK_USERSPACE_IMPLEMENTATION=wireguard-go
      - USE_RANDOM_ID=true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
    ports:
      - "44001:44000"
      - "43129:43128"
      - "41081:41080"
    privileged: true
    pid: "host"

  edge_agent_test:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/edge_agent/Dockerfile
    image: local_edge_agent
    container_name: local_edge_agent_test
    network_mode: host
    depends_on:
      edge_admin:
        condition: service_healthy
      edge_vpn:
        condition: service_healthy
    volumes:
      - ../../edge_agent:/app:z
      - ../../nexmaker:/nexmaker:z
      - local_edge_agent_deps:/app/deps
      - local_edge_agent_build:/app/_build
      - local_edge_agent_data:/app/data
      - local_edge_agent_netclient_data:/etc/netclient
      - /:/host:ro
    env_file:
      - ./.envs/.edge_agent_test
    profiles:
      - test
    privileged: true
    command: mix test
