# deploy/local/edge.yml
networks:
  local_edge_core:
    name: local_edge_core
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  local_registry_data: {}
  local_edge_agent_data: {}
  local_edge_agent_deps: {}
  local_edge_agent_build: {}
  local_edge_agent_2_data: {}
  local_edge_agent_2_deps: {}
  local_edge_agent_2_build: {}

services:
  # Edge Agents
  edge_agent:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/edge_agent/Dockerfile
    image: localhost:45000/edge_agent:stable
    container_name: local_edge_agent
    volumes:
      - ../../edge_agent:/app:z
      - ../../nexmaker:/nexmaker:z
      - local_edge_agent_deps:/app/deps
      - local_edge_agent_build:/app/_build
      - local_edge_agent_data:/app/data
      - /etc/resolv.conf:/etc/resolv.conf:rw
      - /:/host:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    env_file:
      - ./.envs/.edge_agent
    network_mode: host
    privileged: true
    ports:
      - "44000:44000"
      - "43128:43128"
      - "41080:41080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: local_watchtower
    command:
      - --http-api-update
      - --label-enable
      - --cleanup
    env_file:
      - ./.envs/.edge_agent
    networks:
      - local_edge_core
    ports:
      - "58080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  registry:
    image: registry:latest
    container_name: local_registry
    networks:
      - local_edge_core
    ports:
      - "45000:5000"
    volumes:
      - local_registry_data:/var/lib/registry
    environment:
      - OTEL_TRACES_EXPORTER=none
      - OTEL_SDK_DISABLED=true
      - REGISTRY_LOG_LEVEL=warn

  edge_agent_2:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/edge_agent/Dockerfile
    image: local_edge_agent
    container_name: local_edge_agent_2
    networks:
      - local_edge_core
    extra_hosts:
      - "edge-vpn.localtest.me:172.19.0.101"
      - "edge-vpn-broker.localtest.me:172.19.0.101"
    volumes:
      - ../../edge_agent:/app:z
      - ../../nexmaker:/nexmaker:z
      - local_edge_agent_2_deps:/app/deps
      - local_edge_agent_2_build:/app/_build
      - local_edge_agent_2_data:/app/data
      - /:/host:ro
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUBLIC_ENROLLMENT_KEY_URL=http://edge_admin:44000/api/v1/clusters/default/enrollment_keys/public
      - WG_QUICK_USERSPACE_IMPLEMENTATION=wireguard-go
      - USE_RANDOM_ID=true
      - HOST_METRICS_PORT=49101
      - WIREGUARD_METRICS_PORT=49587
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
    ports:
      - "44001:44000"
      - "43129:43128"
      - "41081:41080"
    privileged: true
    profiles:
      - agent-2

  edge_agent_test:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/edge_agent/Dockerfile
    image: local_edge_agent
    container_name: local_edge_agent_test
    network_mode: host
    volumes:
      - ../../edge_agent:/app:z
      - ../../nexmaker:/nexmaker:z
      - local_edge_agent_deps:/app/deps
      - local_edge_agent_build:/app/_build
      - local_edge_agent_data:/app/data
      - /:/host:ro
    env_file:
      - ./.envs/.edge_agent_test
    profiles:
      - test
    privileged: true
    command: mix test
