# deploy/local/web.yml
networks:
  local_edge_core:
    name: local_edge_core

volumes:
  local_edge_admin_db_data: {}
  local_edge_admin_db_data_backups: {}
  local_edge_admin_deps: {}
  local_edge_admin_build: {}

services:
  edge_admin_db:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/postgres/Dockerfile
    image: local_edge_admin_db
    container_name: local_edge_admin_db
    networks:
      - local_edge_core
    volumes:
      - local_edge_admin_db_data:/var/lib/postgresql/data
      - local_edge_admin_db_data_backups:/backups
    env_file:
      - ./.envs/.edge_admin_db
  
  edge_admin:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/edge_admin/Dockerfile
    image: local_edge_admin
    container_name: local_edge_admin
    networks:
      - local_edge_core
    depends_on:
      - edge_admin_db
    volumes:
      - ../../edge_admin:/app:z
      - local_edge_admin_deps:/app/deps
      - local_edge_admin_build:/app/_build
    env_file:
      - ./.envs/.edge_admin
    ports:
      - "4000:4000"
    command: /start