# edge_admin/lib/edge_admin_web/plugs/agent_auth.ex
defmodule EdgeAdminWeb.Plugs.AgentAuth do
  @moduledoc """
  Plug for agent authentication.

  Validates that requests from agents include a valid api_token in the Authorization header.
  The api_token is generated by the admin during agent registration and must match
  the token stored in the database for that agent.

  ## Usage

      plug EdgeAdminWeb.Plugs.AgentAuth

  ## Authentication

  Requires `Authorization: Bearer <api_token>` header.
  The token is validated against the agents table in the database.
  """

  import Phoenix.Controller
  import Plug.Conn

  alias EdgeAdmin.Nodes.Schemas.Node
  alias EdgeAdmin.Repo

  def init(opts) do
    Keyword.get(opts, :node_lookup, &__MODULE__.default_lookup/1)
  end

  def default_lookup(token) do
    case Repo.get_by(Node, api_token: token) do
      %Node{} = node -> {:ok, Repo.preload(node, :cluster)}
      nil -> :error
    end
  end

  def call(conn, node_lookup) do
    case get_req_header(conn, "authorization") do
      ["Bearer " <> token] ->
        validate_agent_token(conn, token, node_lookup)

      _ ->
        conn
        |> put_status(:unauthorized)
        |> json(%{error: "Unauthorized"})
        |> halt()
    end
  end

  defp validate_agent_token(conn, token, node_lookup) do
    case node_lookup.(token) do
      {:ok, node} ->
        assign(conn, :current_node, node)

      :error ->
        conn
        |> put_status(:unauthorized)
        |> json(%{error: "Unauthorized"})
        |> halt()
    end
  end
end
