# edge_admin/lib/edge_admin_web/plugs/agent_auth.ex
defmodule EdgeAdminWeb.Plugs.AgentAuth do
  @moduledoc """
  Plug for agent authentication.

  Validates that requests from agents include a valid api_token in the Authorization header.
  The api_token is generated by the admin during agent registration and must match
  the token stored in the database for that agent.

  ## Usage

      plug EdgeAdminWeb.Plugs.AgentAuth

  ## Authentication

  Requires `Authorization: Bearer <api_token>` header.
  The token is validated against the agents table in the database.
  """

  import Phoenix.Controller
  import Plug.Conn

  def init(opts), do: opts

  def call(conn, _opts) do
    case get_req_header(conn, "authorization") do
      ["Bearer " <> token] ->
        validate_agent_token(conn, token)

      _ ->
        conn
        |> put_status(:unauthorized)
        |> json(%{error: "Unauthorized"})
        |> halt()
    end
  end

  defp validate_agent_token(conn, token) do
    alias EdgeAdmin.Nodes.Schemas.Node
    alias EdgeAdmin.Repo

    case Repo.get_by(Node, api_token: token) do
      %Node{} = node ->
        # Assign node to connection (like current_user pattern)
        assign(conn, :current_node, node)

      nil ->
        conn
        |> put_status(:unauthorized)
        |> json(%{error: "Unauthorized"})
        |> halt()
    end
  end
end
