# edge_admin/lib/edge_admin_web/plugs/agent_auth.ex
defmodule EdgeAdminWeb.Plugs.AgentAuth do
  @moduledoc """
  Plug for agent authentication.

  Validates that requests from agents include a valid api_token in the Authorization header.
  The api_token is generated by the admin during agent registration and must match
  the token stored in the database for that agent.

  ## Usage

      plug EdgeAdminWeb.Plugs.AgentAuth

  ## Authentication

  Requires `Authorization: Bearer <api_token>` header.
  The token is validated against the agents table in the database.
  """

  import Plug.Conn
  import Phoenix.Controller

  def init(opts), do: opts

  def call(conn, _opts) do
    case get_req_header(conn, "authorization") do
      ["Bearer " <> token] ->
        validate_agent_token(conn, token)

      _ ->
        conn
        |> put_status(:unauthorized)
        |> json(%{error: "Unauthorized"})
        |> halt()
    end
  end

  defp validate_agent_token(conn, token) do
    # TODO: Implement token validation against database
    # For now, this is a placeholder that always fails
    # Implementation will query the agents table for matching api_token
    conn
    |> put_status(:unauthorized)
    |> json(%{error: "Unauthorized"})
    |> halt()
  end
end
