#!/bin/sh
# deploy/production/compose/edge_metrics_collector/entrypoint

set -o errexit
set -o pipefail
set -o nounset

echo "Initialize Edge Metrics Collector..."

# Execute the command passed to the container
exec "$@"