# deploy/production/compose/edge_metrics_collector/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "edge-nodes"
    http_sd_configs:
      - url: "http://edge_admin:44000/api/nodes/metrics/host/discovery"
    authorization:
      type: Bearer
      credentials: supersecretkey123456789

  - job_name: "edge-metrics-collector"
    static_configs:
      - targets: ["localhost:8429"]
    metrics_path: "/metrics"

  - job_name: "edge-metrics-storage"
    static_configs:
      - targets: ["edge_metrics_storage:8428"]
    metrics_path: "/metrics"

  - job_name: "edge-admin"
    static_configs:
      - targets: ["edge_admin:44000"]
    metrics_path: "/api/admins/metrics/self/raw"
