# deploy/production/compose/edge_metrics_collector/prometheus.yml
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "node-host-metrics"
    http_sd_configs:
      - url: "http://edge_admin_a1:44000/api/v1/nodes/metrics/host/discovery"
        authorization:
          type: Bearer
          credentials: supersecretkey123456789
    authorization:
      type: Bearer
      credentials: supersecretkey123456789

  - job_name: "node-agent-metrics"
    http_sd_configs:
      - url: "http://edge_admin_a1:44000/api/v1/nodes/metrics/agent/discovery"
        authorization:
          type: Bearer
          credentials: supersecretkey123456789
    authorization:
      type: Bearer
      credentials: supersecretkey123456789

  - job_name: "node-wireguard-metrics"
    http_sd_configs:
      - url: "http://edge_admin_a1:44000/api/v1/nodes/metrics/wireguard/discovery"
        authorization:
          type: Bearer
          credentials: supersecretkey123456789
    authorization:
      type: Bearer
      credentials: supersecretkey123456789

  - job_name: "edge-metrics-collector"
    static_configs:
      - targets: ["localhost:8429"]
    metrics_path: "/metrics"

  - job_name: "edge-metrics-storage"
    static_configs:
      - targets: ["edge_metrics_storage:8428"]
    metrics_path: "/metrics"

  - job_name: "admin-metrics"
    static_configs:
      - targets: ["edge_admin_a1:44000", "edge_admin_a2:44000", "edge_admin_b1:44000"]
    metrics_path: "/api/v1/admins/metrics/self/raw"
    authorization:
      type: Bearer
      credentials: supersecretkey123456789
