# deploy/production/edge.test.yml
networks:
  production_edge_core:
    name: production_edge_core
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  production_edge_agent_data: {}
  production_registry_data: {}

services:
  edge_agent:
    build:
      context: ../..
      dockerfile: ./deploy/production/compose/edge_agent/Dockerfile
    image: localhost:45000/edge_agent:stable
    container_name: production_edge_agent
    volumes:
      - production_edge_agent_data:/app/data
      - /etc/resolv.conf:/etc/resolv.conf:rw
      - /:/host:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    env_file:
      - ./.envs/.edge_agent
    environment:
      - PUBLIC_ENROLLMENT_KEY_URL=http://edge-admin.localtest.me/api/v1/clusters/default/enrollment_keys/public
      - NETMAKER_API_SCHEME=http
    network_mode: host
    privileged: true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: production_watchtower
    command:
      - --http-api-update
      - --label-enable
      - --cleanup
    env_file:
      - ./.envs/.edge_agent
    networks:
      - production_edge_core
    ports:
      - "58080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  registry:
    image: registry:2
    container_name: production_registry
    networks:
      - production_edge_core
    ports:
      - "45000:5000"
    volumes:
      - production_registry_data:/var/lib/registry
