# deploy/production/edge.yml
networks:
  production_edge_core:
    name: production_edge_core

volumes:
  production_edge_agent_data: {}
  production_edge_agent_netclient_data: {}

services:
  # Edge Agent
  edge_agent:
    build:
      context: ../..
      dockerfile: ./deploy/production/compose/edge_agent/Dockerfile
    image: production_edge_agent
    container_name: production_edge_agent
    network_mode: host
    volumes:
      - production_edge_agent_data:/app/data
      - production_edge_agent_netclient_data:/etc/netclient
      - /:/host:ro
    env_file:
      - ./.envs/.edge_agent
    privileged: true
    command: /start
