# deploy/production/web.yml
networks:
  production_edge_core:
    name: production_edge_core

volumes:
  production_edge_admin_db_data: {}
  production_edge_admin_db_data_backups: {}
  production_edge_vpn_data: {}
  production_edge_admin_tailscale_data: {}

services:
  # Edge Admin
  edge_admin_db:
    build:
      context: ../..
      dockerfile: ./deploy/production/compose/postgres/Dockerfile
    image: production_edge_admin_db
    container_name: production_edge_admin_db
    networks:
      - production_edge_core
    volumes:
      - production_edge_admin_db_data:/var/lib/postgresql/data
      - production_edge_admin_db_data_backups:/backups
    env_file:
      - ./.envs/.edge_admin_db

  edge_admin:
    build:
      context: ../..
      dockerfile: ./deploy/production/compose/edge_admin/Dockerfile
    image: production_edge_admin
    container_name: production_edge_admin
    networks:
      - production_edge_core
    depends_on:
      - edge_admin_db
      - edge_vpn
    volumes:
      - production_edge_admin_tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    env_file:
      - ./.envs/.edge_admin
    ports:
      - "4000:4000"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    command: ["sh", "-c", "/app/bin/migrate && /app/bin/server"]

  # Edge VPN
  edge_vpn:
    build:
      context: ../..
      dockerfile: ./deploy/production/compose/edge_vpn/Dockerfile
    container_name: production_edge_vpn
    volumes:
      - ../../deploy/production/compose/edge_vpn/headscale_config:/etc/headscale
      - production_edge_vpn_data:/var/lib/headscale
    ports:
      - "8080:8080"  # Headscale
      - "8081:8081"  # VPN Wrapper
      - "9090:9090"  # Metrics
    networks:
      - production_edge_core
    command: /start