# edge_agent/lib/edge_agent_web/endpoint.ex
defmodule EdgeAgentWeb.Endpoint do
  @moduledoc """
  Phoenix endpoint for the agent's HTTP API.

  Liveness replies are handled before request-id assignment. Readiness checks,
  metrics, and REST routes are then dispatched through their dedicated plugs
  and routers. Security headers run first, and request IDs are generated by
  `EdgeAgentWeb.Plugs.AssignRequestId`; inbound request IDs are ignored.
  """

  use Phoenix.Endpoint, otp_app: :edge_agent

  alias Plug.Conn

  plug(EdgeAgentWeb.Plugs.Security)
  plug(:ping)

  if code_reloading? do
    plug(Phoenix.CodeReloader)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :edge_agent)
  end

  # AssignRequestId both generates a UUID and sets the response header, so
  # `Plug.RequestId` is redundant. Agent is a request origin, not a relay —
  # we don't honor inbound x-request-id from upstream.
  plug(EdgeAgentWeb.Plugs.AssignRequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(
    Plug.Parsers,
    parsers: [:json],
    pass: ["application/json"],
    json_decoder: Phoenix.json_library()
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)

  plug(EdgeAgentHealth.Router)
  plug(:halt_if_sent)

  plug(:metrics_auth_conditional)
  plug(:prom_ex_metrics)

  plug(EdgeAgentWeb.Router)

  # sobelow_skip ["XSS.SendResp"]
  defp ping(%{request_path: path} = conn, _opts) when path in ["/ping", "/livez"] do
    version = Application.get_env(:edge_agent, :version)
    response = JSON.encode!(%{status: "ok", version: version})

    conn
    |> Conn.put_resp_header("content-type", "application/json")
    |> Conn.send_resp(200, response)
    |> Conn.halt()
  end

  defp ping(conn, _opts), do: conn

  defp metrics_auth_conditional(%{request_path: "/api/v1/agents/me/metrics/raw"} = conn, _opts) do
    if Application.get_env(:edge_agent, :agent_metrics_dedicated, false) do
      conn
    else
      auth_enabled = Application.get_env(:edge_agent, :agent_metrics_auth_enabled, true)

      if auth_enabled do
        EdgeAgentWeb.Plugs.ApiTokenAuth.call(conn, [])
      else
        conn
      end
    end
  end

  defp metrics_auth_conditional(conn, _opts), do: conn

  defp prom_ex_metrics(conn, _opts) do
    if Application.get_env(:edge_agent, :agent_metrics_dedicated, false) do
      conn
    else
      PromEx.Plug.call(
        conn,
        PromEx.Plug.init(prom_ex_module: EdgeAgent.PromEx, path: "/api/v1/agents/me/metrics/raw")
      )
    end
  end

  # Splitting routers in separate modules has a negative side effect:
  # Phoenix.Router does not check the Plug.Conn state and tries to match the
  # route even if it was already handled/sent by another router.
  defp halt_if_sent(%{state: :sent, halted: false} = conn, _opts), do: halt(conn)
  defp halt_if_sent(conn, _opts), do: conn
end
