#!/bin/bash
# deploy/local/compose/edge_agent/start

set -o errexit
set -o pipefail
set -o nounset

mix deps.get
mix compile
mix ecto.migrate

# Start the development server with hot reloading
echo "Starting Phoenix server..."
export PHX_SERVER=true
exec mix phx.server
