# edge_admin/lib/edge_admin/nodes/cluster.ex
defmodule EdgeAdmin.Nodes.Cluster do
  @moduledoc """
  Schema for edge clusters. Each cluster represents an isolated Netmaker network
  with its own IPv4 range.
  """
  use EdgeAdmin.Schema

  alias EdgeAdmin.Vpn

  schema "clusters" do
    field(:name, :string)
    field(:ipv4_range, :string)
    field(:node_count, :integer, virtual: true)

    has_many(:nodes, EdgeAdmin.Nodes.Node)

    timestamps()
  end

  @doc false
  def changeset(cluster, attrs) do
    cluster
    |> cast(attrs, [:name, :ipv4_range])
    |> maybe_generate_name()
    |> maybe_generate_ipv4_range()
    |> validate_required([:name, :ipv4_range])
    |> validate_length(:name, max: 24)
    |> validate_format(:name, ~r/^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/)
    |> validate_ipv4_cidr_format()
    |> validate_ipv4_exclusions()
    |> unique_constraint(:name)
    |> unique_constraint(:ipv4_range)
  end

  @doc """
  Returns the Netmaker network name for this cluster.
  Format: cluster-{name}
  """
  def network_name(%__MODULE__{name: name}), do: Vpn.cluster_network_name(name)

  @doc """
  Returns the DNS domain suffix for nodes in this cluster.
  Format: cluster-{name}.{domain}
  where domain is configured via NETMAKER_DEFAULT_DOMAIN (default: nm.internal)
  """
  def dns_domain(%__MODULE__{name: name}) do
    Vpn.build_domain(Vpn.cluster_network_name(name))
  end

  # Private helper functions

  defp maybe_generate_name(changeset) do
    if get_field(changeset, :name) do
      changeset
    else
      # Generate 12-char random alphanumeric name
      random_name =
        :crypto.strong_rand_bytes(9)
        |> Base.encode32(case: :lower, padding: false)
        |> String.slice(0..11)

      put_change(changeset, :name, random_name)
    end
  end

  defp maybe_generate_ipv4_range(changeset) do
    if get_field(changeset, :ipv4_range) do
      changeset
    else
      # Will be generated by Nodes context if needed
      changeset
    end
  end

  # Private validation functions

  defp validate_ipv4_cidr_format(changeset) do
    validate_change(changeset, :ipv4_range, fn _, value ->
      case Vpn.parse_cidr(value) do
        {:ok, _} -> []
        {:error, reason} -> [ipv4_range: reason]
      end
    end)
  end

  defp validate_ipv4_exclusions(changeset) do
    validate_change(changeset, :ipv4_range, fn _, value ->
      case Vpn.parse_cidr(value) do
        {:ok, {ip_tuple, _prefix}} ->
          if excluded_range?(ip_tuple) do
            [ipv4_range: "cannot use private, loopback, link-local, or multicast ranges"]
          else
            []
          end

        {:error, _} ->
          []
      end
    end)
  end

  defp excluded_range?({a, _, _, _}) do
    a in [0, 10, 127, 169, 172, 192, 224, 240, 255]
  end
end
